### ISSUE TITLE
Bulk Role Addition / Removal

### ISSUE THREAD

**Issue by TangoCantCode** [Hirakudev/Exult-Bot-Rewrite#25]
Similar to dyno's ?role all.
Ideally would have a command such as e!role <add/remove> <all/userswithcertainrole><role>

- [x] e!role add all <role>
- [x] e!role remove all <role>
- [x] e!role add <userswithcertainrole> <role>
- [x] e!role remove <userswithcertainrole> <role>

**Comment by Hirakudev** [comment]
Since the bot is moving to slash commands only, it won't require a prefix. I'll add this to the projects tab still though, thanks!

**Comment by pikaninja** [comment]
This isn't possible for slash command structure. Please propose new structure ty i have no ideas

**Comment by Hirakudev** [comment]
Completed entirely in slash commands (not message commands as specified in the issue's body).

Not sure if this will make the live bot though due to rate-limiting issues.
